version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: intellikit-postgres
    environment:
      POSTGRES_DB: intellikit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: intellikit-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: intellikit
      NEST_PUBLIC_GEMINI_API_KEY: ${NEST_PUBLIC_GEMINI_API_KEY}
      NODE_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: 